FROM java

LABEL maintainer "misha.yang@daocloud.io"

COPY /project/target/docker_spring_boot.jar  /usr/src/myapp/labs-demo-0.0.1-SNAPSHOT.jar

WORKDIR /usr/src/myapp/

ENTRYPOINT java -jar labs-demo-0.0.1-SNAPSHOT.jar